### ISSUE TITLE
[QUESTION] USDC specification

### ISSUE THREAD

**Issue by MrMuetze** [syoyo/tinyusdz#11]
Hi,
I was encouraged to open an issue for this question that I have: I see that you are already able to read usdc without any external dependencies and I wanted to ask if you used some kind of file format specification or if you manually figured out the usdc file format.

I am the developer of an iOS AR app that visualizes models that have been converted from 3D geological models into usda. For this purpose I have written a rudimentary usda writer that that converts these simple TINs. In my specific case, I cannot rely on tools such as "usdcat", Xcode or libraries like the Pixar USD library to convert anything into usdc and I aim to write a rudimentary usdc writer.

(Edit: the models are converted on a server running rust, that is the location where the app downloads them from)

While searching for a usdc specification, I stumbled over this exciting project and wanted to ask if you have access to such a specification :) if not, I will try to dive deeper into this repository.

Best regards!
Björn

**Comment by meshula** [comment]
It's not the answer to your question, but the ModelIO framework in iOS can output usdc files. That would be an easy way to get an iOS app to export usdc, without needing to introduce libraries or external code, beyond what Apple provides anyway. It's straight forward to set up a MDLAsset with a MDLMesh: https://developer.apple.com/documentation/modelio/mdlmesh?language=objc

**Comment by MrMuetze** [comment]
Thank you very much for that suggestion. I just noticed that I forgot to mention that the models are converted on a server running rust from which the app will download them.

Nevertheless I will have a look at the ModelIO framework and see if I can make something work. Your comment is definitely appreciated :)

**Comment by meshula** [comment]
Cheers :) If you are running rust on a server, there's also an option of using the usd-rs crate, btw. https://github.com/luke-titley/usd-rs

**Comment by syoyo** [comment]
@MrMuetze For USDC, as @meshula describes there is no standarized/official specification of USDC. It looks the code is low. You need to look into the source code to understand the specification/file format.

https://github.com/syoyo/tinyusdz/blob/master/doc/usdc_format.md

NOTE: There is neither specification(schema) nor source code for Apple extension to USDC(e.g. Metadata in Reality Composer exported USDZ/USDC)

**Comment by MrMuetze** [comment]
@meshula sadly, the "usd-rs" crate provides just the bindings to the Pixar USD library, although it seems to integrate it rather nicely. I will have to check how I could use this crate after building it, maybe it's easier to handle then other solutions.

@syoyo thank you very much! I will see if I can figure something out with your docs and code :)

**Comment by meshula** [comment]
Helpfully, Apple's ARKit schemas are documented. https://developer.apple.com/documentation/arkit/usdz_schemas_for_ar?language=objc 

At least the USDZ container is clearly specified, but that specification doesn't extend to the USDC files embedded in it. https://graphics.pixar.com/usd/docs/Usdz-File-Format-Specification.html

**Comment by syoyo** [comment]
@meshula I meant schema in .usda file. Also, ARKit documentations is not Apache 2.0 license, so we cannot convert it to .usda and distribute it.

**Comment by meshula** [comment]
Ah, I see what you mean.

**Comment by syoyo** [comment]
@meshula For some reason, Apple released ARKit related schema with permissive license 👍 https://developer.apple.com/documentation/arkit/usdz_schemas_for_ar/schema_definitions_for_third-party_digital_content_creation_dcc

**Comment by syoyo** [comment]
Still no official USDC(Crate) format specification.

Someone may be working on it at https://wiki.aswf.io/display/WGUSD/USD+Working+Group  but I'm not sure.   Reading pxrUSD source code is the solution for now.

**Comment by syoyo** [comment]
👀 https://github.com/PixarAnimationStudios/USD/pull/2086
