### ISSUE TITLE
Shader error ?

### ISSUE THREAD

**Issue by MootoolsSoftware** [syoyo/tinyusdz#112]
Model: [Netsuke_-_Shoki_capturing_an_oni.zip](https://github.com/syoyo/tinyusdz/files/13726039/Netsuke_-_Shoki_capturing_an_oni.zip)
Source: [Sketchfab](https://sketchfab.com/3d-models/netsuke-shoki-capturing-an-oni-350423d0c7d045a7bd89b1814772399d)

Reproduce code:

```
tydra_to_renderscene.exe "Netsuke_-_Shoki_capturing_an_oni.usdz"
````

Parsing the following model return an error on windows:
![image](https://github.com/syoyo/tinyusdz/assets/15813085/97908235-39ec-4f34-af1a-1fed7d614986)

Is this a problem in the shader or the model?
We can't decode the error and are not able to know if this is a lib limitation or conversion problem.

**Comment by syoyo** [comment]
As the message says, `outputs:rgb` is supported but `outputs:r` is not yet supported in TinyUSDZ Tydra API

https://openusd.org/release/spec_usdpreviewsurface.html#texture-reader

This will be implemented along with USD to RenderMesh conversion task https://github.com/syoyo/tinyusdz/issues/109

**Comment by syoyo** [comment]
Supported `outputs:r`(and others) in recent `dev` branch.

https://github.com/syoyo/tinyusdz/commit/81f7d7cf8a144ebc2273a0b13edaecc77d603ca7
https://github.com/syoyo/tinyusdz/commit/63203fc16a565d3497a5e9e39fa58449adbbcb0c

And now `tydra::DumpRenderScene` prints `outputChannel` parameter

```
$ ./tydra_to_renderscene Netsuke_-_Shoki_capturing_an_oni.usdz

...
textures {
[0] UVTexture {
        primvar_name st0
        outputChannel rgb
        bias (0, 0, 0, 0)
        scale (1, 1, 1, 1)
        wrapS repeat
        wrapT repeat
        fallback_uv (0, 0, 0, 0)
        textureImageID 0
        has UsdTransform2d 0

    }
[1] UVTexture {
        primvar_name st0
        outputChannel r
        bias (0, 0, 0, 0)
        scale (1, 1, 1, 1)
        wrapS repeat
        wrapT repeat
        fallback_uv (0, 0, 0, 0)
        textureImageID 1
        has UsdTransform2d 0

    }
[2] UVTexture {
        primvar_name st0
        outputChannel r
        bias (0, 0, 0, 0)
        scale (1, 1, 1, 1)
        wrapS repeat
        wrapT repeat
        fallback_uv (0, 0, 0, 0)
        textureImageID 2
        has UsdTransform2d 0

    }
}
```
