### ISSUE TITLE
Android example should be removed, not yet ready for public exposure

### ISSUE THREAD

**Issue by tellypresence** [syoyo/tinyusdz#127]
Out of the box, the android example builds/launches OK, but USD asset fails to load and toast displayed: `Failed to load USD file`
<img src="https://github.com/syoyo/tinyusdz/assets/26958898/e0a8b5e6-15a9-48eb-96da-4a275eb72148" alt="tinyusdz_android_example_asset_load_fail" width=180 />

Looks like this project isn't ready for public consumption, C++ `initScene()` hardcodes "success" return code of `0`, but `MainActivity` considers `0` to be failure.  Looks like there's a bunch of commented out lines with `TODO`s, apparently `tinyusdz::Stage` doesn't yet support actual geometry, i.e. `Stage::geom_meshes` referred to in commented-out code but doesn't exist yet

**Comment by syoyo** [comment]
Android example is TODO https://github.com/syoyo/tinyusdz/discussions/105#discussioncomment-7661115

**Comment by tellypresence** [comment]
Was just about to close this as I found [105](https://github.com/syoyo/tinyusdz/discussions/105) -- sorry for the duplicate
