### ISSUE TITLE
[Branch "dev"] Crash when loading usd-wg vechicle "geo" models

### ISSUE THREAD

**Issue by tellypresence** [syoyo/tinyusdz#129]
(update: these models load OK on `rendermesh-refactor` branch, should be able to close this once merged back to `dev`)

Steps to reproduce:
- On `dev` branch, attempt to load model [`4wdGeo.usd`](https://github.com/usd-wg/assets/blob/main/full_assets/Vehicles/USD_Mini_Car_Kit/assets/vehicles/4wd/geo/4wdGeo.usd)

With verbose logging enabled, will see the following logged; after line `renderMaterialId = -1` the application crashes
```
tinyusdz_repo/src/tydra/scene-access.cc:BuildXformNodeFromStageRec:2102 Not xformable
tinyusdz_repo/src/tydra/render-data.cc:MeshVisitor:2392 Material: </_wd>
tinyusdz_repo/src/stage.cc:GetPrimAtPath:97 GetPrimAtPath : /_wd(input path: </_wd>)
tinyusdz_repo/src/stage.cc:GetPrimAtPath:117 clear cache.
tinyusdz_repo/src/tydra/shader-network.cc:operator():275 GPrim has no materialBinding.
tinyusdz_repo/src/tydra/shader-network.cc:FindBoundMaterial:327 search parent: /_wd
tinyusdz_repo/src/stage.cc:GetPrimAtPath:97 GetPrimAtPath : /_wd(input path: </_wd>)
tinyusdz_repo/src/stage.cc:GetPrimAtPath:126 Found cache.
tinyusdz_repo/src/tydra/shader-network.cc:operator():275 GPrim has no materialBinding.
tinyusdz_repo/src/tydra/render-data.cc:ConvertMesh:1235 num_fvs = 1836
tinyusdz_repo/src/tydra/render-data.cc:MeshVisitor:2477 renderMaterialId = -1
```

Note: these models are also observed to reliably crash in similar fashion:
- [`ambulanceGeo.usd`](https://github.com/usd-wg/assets/blob/main/full_assets/Vehicles/USD_Mini_Car_Kit/assets/vehicles/ambulance/geo/ambulanceGeo.usd)
- [`formulaGeo.usda`](https://github.com/usd-wg/assets/blob/main/full_assets/Vehicles/USD_Mini_Car_Kit/assets/vehicles/formula/geo/formulaGeo.usda)

Please check results and see if the failure can be dealt with gracefully, thank you

**Comment by syoyo** [comment]
You should describe mode details on reproducing procedure and error.

At least `tusdcat 4wdGeo.usd` works well and does not crash.

**Comment by tellypresence** [comment]
NOTE: these models load OK on `rendermesh-refactor` branch, must have fixed something

(ignore the broken faces, that's a known separate issue)

<table>
<tr><th rowspan=2>Model</th><th colspan=2>Screenshots</th></tr>
<tr><th>Solid</th><th>Wireframe</th></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/full_assets/Vehicles/USD_Mini_Car_Kit/assets/vehicles/4wd/geo/4wdGeo.usd"><tt>4wdGeo.usd</tt></a></td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/8339b5b6-eec3-41d1-8361-a3d0807b83e3" width=90></td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/fc89fbbb-e662-4b17-9972-8a0d706e4293" width=90></td></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/full_assets/Vehicles/USD_Mini_Car_Kit/assets/vehicles/ambulance/geo/ambulanceGeo.usd"><tt>ambulanceGeo.usd</tt></a></td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/23cc6aaf-d67f-4225-8e51-ebadf5f2825f" width=90></td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/a87a98f1-e56a-41f7-8591-d9a9e24ac710" width=90></td></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/full_assets/Vehicles/USD_Mini_Car_Kit/assets/vehicles/ambulance/geo/sedanGeo.usd"><tt>sedanGeo.usd</tt></a></td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/ef77774c-b9ea-4ee2-99fa-c3a3c35236a3" width=90></td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/4bc40eca-53d9-4635-8cc6-2ea0be7d5472" width=90></td></tr>
</table>

**Comment by syoyo** [comment]
`tusdcat 4wdGeo.usd` also works on `dev` branch.
