### ISSUE TITLE
[Branch "rendermesh-refactor"] Mesh material indices broken

### ISSUE THREAD

**Issue by tellypresence** [syoyo/tinyusdz#131]
On `dev` branch, `RenderMesh` mesh objects provided valid material ID array which could be used for assigning material index e.g. by using the first element for the entire mesh:
`render_scene.meshes[meshIdx].materialIds[0]`

On `rendermesh-refactor` branch, `RenderMesh` mesh objects modified so there's now a `material_id` e.g.
`render_scene.meshes[meshIdx].material_id;`
But these values don't ever seem to be assigned and are left at default `-1` so they aren't useful for material lookup.

<table>
<tr><th rowspan=2>Branch</th><th rowspan=2>Model</th><th colspan=2>Screenshots</th><th rowspan=2>Notes</th></tr>
<tr><th>Appearance</th><th>Material IDs detail</th></tr>
<tr><td><tt>rendermesh-refactor</tt></td><td rowspan=2><a href="https://github.com/usd-wg/assets/blob/main/test_assets/USDZ/BrainStem/BrainStem.usdz"><tt>BrainStem.usdz</tt></a><br>(<a href="https://github.com/usd-wg/assets">usd-wg/assets</a>)</td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/30eba62f-8ece-46d7-a687-77411aba2c71" width=90></td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/f5cb3d81-b507-40ae-a276-2f51ef3ec0c1" width=90></td><td>On <tt>rendermesh-refactor</tt> branch, model has 59 materials, but material indices from RenderMesh object have default `-1` value, so meshes unable to find associated material and all pick up material 0 (default index), as can be seen in material IDs detail screenshot (meshes 55, 56, 57 and 58 all have <tt>mtl: 0</tt>)</td></tr>
<tr><td><tt>dev</tt></td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/84aeed09-77b5-471d-be38-b165bbc7e870" width=90></td><td><img src="https://github.com/syoyo/tinyusdz/assets/26958898/c1c9dfd2-e00d-4328-b732-edcbc1b248c3" width=90></td><td>On <tt>dev</tt> branch,  model has 59 materials and per-mesh material indices are correct; each mesh has corresponding material ID as can be seen in material IDs detail screenshot  (mesh 55 has <tt>mtl: 55</tt>, mesh 56 has <tt>mtl: 56</tt> etc)</td></tr>
</table>

**Comment by syoyo** [comment]
Material representation has been changed in `rendermesh-refactor` to support per-face material through GeomSubset.

See 
https://github.com/syoyo/tinyusdz/blob/rendermesh-refactor/src/tydra/obj-export.cc and use https://github.com/syoyo/tinyusdz/blob/rendermesh-refactor/models/geomsubset-material-001.usda to how to access material info assigned to a mesh.

**Comment by tellypresence** [comment]
Confirm that material indices appear to be working now on `rendermesh-refactor` branch, thank you
どうもご苦労様でした
