### ISSUE TITLE
No animations for animated models

### ISSUE THREAD

**Issue by tellypresence** [syoyo/tinyusdz#132]
On branch `rendermesh-refactor` or `dev`

For animated model [`BrainStem.usdz`](https://github.com/usd-wg/assets/blob/main/test_assets/USDZ/BrainStem/BrainStem.usdz), value of `render_scene.animations.size()` is 0.  Expectation is there should be at least 1 animation for this model: 
<img src="https://github.com/usd-wg/assets/blob/main/test_assets/USDZ/BrainStem/screenshot/USDView_BrainStem.gif?raw=true" width=300 />

For animated model [`CesiumMan.usdz`](https://github.com/usd-wg/assets/blob/main/test_assets/USDZ/CesiumMan/CesiumMan.usdz), value of `render_scene.animations.size()` is 0.  Expectation is there should be at least 1 animation for this model: 
<img src="https://github.com/usd-wg/assets/blob/main/test_assets/USDZ/CesiumMan/screenshot/USDView_CesiumMan.gif?raw=true" width=300 />

**Comment by syoyo** [comment]
https://github.com/syoyo/tinyusdz/issues/148
