### ISSUE TITLE
Embedded texture buffer empty

### ISSUE THREAD

**Issue by tellypresence** [syoyo/tinyusdz#134]
On branch `rendermesh-refactor` or `dev`

When loading model [`CesiumMan.usdz`](https://github.com/usd-wg/assets/blob/main/test_assets/USDZ/CesiumMan/CesiumMan.usdz)

`render_scene.images[0].asset_identifier` is correctly populated as `0/CesiumMan_img0.jpg`, but `width`, `height` set to`-1`.

`render_scene.images[0].buffer_id` field is `0`, but corresponding buffer for that (apparently correct) id of `0` has `render_scene.buffers[0].size()` of  `0`, i.e. image data buffer empty

**Comment by syoyo** [comment]
Currently TinyUSDZ Tydra only supports loading texture from file, and does not load asset from memory(USDZ ZIP container).

https://github.com/syoyo/tinyusdz/blob/caa6d877ff5448a3b1ca48497e0a07f374b5098c/src/tydra/render-data.cc#L2599

Reading texture asset from USDZ container is todo:

- [x] Setup AssetResolution to read an asset from USDZ container
- [x] Use `tinyusdz::image::LoadImageFromMemory` to load texture

**Comment by syoyo** [comment]
`tydra_to_renderscene` example in recent `rendermesh-refactor` branch now able to read asset in USDZ.

```
$ tydra_to_renderscene models/texture-cat-plane.usdz

...

images {
[0] TextureImage {
        asset_identifier "./textures/texture-cat.jpg"
        channels 4
        width 768
        height 768
        miplevel 0
        colorSpace srgb
        bufferID 0

    }
}

buffers {
[0] Buffer {
        bytes 9437184
        componentType float
    }
}
```

**Comment by tellypresence** [comment]
In recent `rendermesh-refactor` branch, embedded textures working well
<img src="https://github.com/syoyo/tinyusdz/assets/26958898/ecc14f64-8f62-4444-85f9-08482a8e2e06" width=90 />
