### ISSUE TITLE
 Is there a way to perform asset resolution?

### ISSUE THREAD

**Issue by MootoolsSoftware** [syoyo/tinyusdz#140]
We are using TinyUSD and we currently have difficulties with asset identifier.

```
tinyusdz::tydra::RenderSceneConverter converter;
tinyusdz::tydra::RenderScene renderScene;
ret = converter.ConvertToRenderScene(stage, &renderScene);
```
After calling ConvertToRenderScene, your lib returns textures/images containing only asset_identifier.

So the question is : how to get the full file path on disk or to get access to the unpack texture embed in the usdz file?

We have noticed that all asset_identifiers were starting by 0 (0/TheTexture.jpg).

* Does the 0 is related to a folder name "0" or is it an internal tag?
* The patch seems to correspond to a ressource which is in the usd file? If so, how to get access to the ressource through the lib?
* What is the way to perform asset resolution in a general an universal way (whatever the file is, usdz or not)?

#134 might be the beginning of the answer ;-)

Thanks for your help!

**Comment by syoyo** [comment]
Texture loading with user supplied asset resolution is TODO(working in `rendermesh-refactor`)

There is already an interface to provide custom user-defined texture loader callback interface: https://github.com/syoyo/tinyusdz/blob/635d49c1123585bba86ef4c730fce423319b66d5/src/tydra/render-data.hh#L1252 , but need to polish its implementation and API.

For an example of asset_resolution usage in TinyUSDZ, please take a look at `asset_resolution` example: https://github.com/syoyo/tinyusdz/blob/dev/examples/asset_resolution/asset-resolution-example.cc

**Comment by syoyo** [comment]
I have implemented handy API to setup AssetResolutionResolver to load assets from USDZ package, not from filesystem.

https://github.com/syoyo/tinyusdz/blob/00ebed505edddd280a706021ca85af9095c68afb/src/tinyusdz.cc#L1387

Plese use `[rendermesh-refactor](https://github.com/syoyo/tinyusdz/tree/rendermesh-refactor)` branch, and here is an example usage:

https://github.com/syoyo/tinyusdz/blob/00ebed505edddd280a706021ca85af9095c68afb/examples/tydra_to_renderscene/to-renderscene-main.cc#L172

(Please try `tydra_to_renderscene input.usdz` )

**Comment by syoyo** [comment]
Now `rendermesh-refactor` branch is merged into `dev`.  So `SetupUSDZAssetResolution` is now available.

polishing its implementation and API is still TODO, but now it is possible to perform (user-supplied) asset resolution.
