### ISSUE TITLE
ConvertToRenderScene errors on Apple set of file

### ISSUE THREAD

**Issue by MootoolsSoftware** [syoyo/tinyusdz#141]
We use `tinyusdz::tydra::RenderSceneConverter` to perform conversion for our USD reader.

We try it on a set of file provided by Apple ([Quick look gallery](https://developer.apple.com/augmented-reality/quick-look/)).

 `RenderSceneConverter` returns an error on most of the files.
 
The errors are similar to this one:

[chair_swan](https://developer.apple.com/augmented-reality/quick-look/models/redchair/chair_swan.usdz)

> [error]...\tinyusdz\src\tydra\render-data.cc:ConvertUVTexture():1736 Invalid or unsupported token value for 'colorSpace': `sRGB` 
[error]D:\Manu\Dev_Release\Contrib\tinyusdz\src\tydra\render-data.cc:ConvertPreviewSurfaceShaderParam():2149 Failed to convert UVTexture connected to diffuseColor
[error]...\tinyusdz\src\tydra\render-data.cc:ConvertMaterial():2360 Failed to convert UsdPreviewSurface : /chair_swan/Looks/pxrusdpreviewsurface1sg/redchairmaterial
Visit function returned an error for Prim /chair_swan/RedChairFeet (id 15)

Sometime there it can be a little different:

[TV-Set](https://developer.apple.com/augmented-reality/quick-look/models/retrotv/tv_retro.usdz)

> [error]...\tinyusdz\src\tydra\render-data.cc:ConvertUVTexture():1736 Invalid or unsupported token value for 'colorSpace': `Input - Texture - sRGB - Display P3` 
[error]...\tinyusdz\src\tydra\render-data.cc:ConvertPreviewSurfaceShaderParam():2149 Failed to convert UVTexture connected to diffuseColor
[error]...\tinyusdz\src\tydra\render-data.cc:ConvertMaterial():2360 Failed to convert UsdPreviewSurface : /tv_retro/Looks/tv_retro_2_pxrusdpreviewsurface1sg/tv_retro_2_retrotvbodymaterial
Visit function returned an error for Prim /tv_retro/tv_retro_2_tv_retro/tv_retro_2_RetroTVBody (id 24)

**Comment by syoyo** [comment]
Interesting.

Apple's usdz file was updated to add `colorSpace` metadata in asset Attribute.
(At least I cannot find it in TV-Set model downloaded at 2022 Sep)

`colorSpace` metadata support is adding in `rendermesh-refactor` branch(work-in-progress branch), thus `sRGB` should be handled correctly there.

For TV-Set,

```
                asset inputs:file = @0/tv_retro_screen_bc.png@ (
                    colorSpace = "Input - Texture - sRGB - Display P3"
                )
```

I cannot find specification to `colorSpace` metadata  in Apple's USDZ, but it could be inferred as "srgb_displayp3"(colorspace name used in MaterialX)

**Comment by syoyo** [comment]
At least now `sRGB` and `Input - Texture - sRGB - Display P3` are handled well in `dev` branch.

but another error raises in `dev` branch.

```
tinyusdz/src/tydra/render-data.cc:ConvertUVTexture():2030 Failed to evaluate UsdPrimvarReader_float2's inputs:varname.
```

which will be fixed in `rendermesh-refactor` branch. 
Loading Display P3 texture will also be done in `rendermesh-refactor`

**Comment by MootoolsSoftware** [comment]
Thanks!
