### ISSUE TITLE
[rendermesh-refactor branch commit e86a0a5] Regression: many previously working models now fail to load

### ISSUE THREAD

**Issue by tellypresence** [syoyo/tinyusdz#152]
[Update] Seems to have been fixed

[Update] According to [this comment](https://github.com/syoyo/tinyusdz/issues/144#issuecomment-2057975630), loading `.usdz` files on `rendermesh-refactor` branch may be (temporarily?) unavailable (not sure if "assets" refers to 3D models, or just embedded textures) -- all the models listed below are `.usdz` format.  (Having said that, usd-wg `.usdz` test asset `brainstem` still works...)

## NOTE: this is a _regression_, not a stale report

On `rendermesh-refactor` branch commit [`e86a0a5`](https://github.com/syoyo/tinyusdz/commit/e86a0a5697f7070c0ed9cf577c54ef23172b463c), the below models fail to load; they were all working a few days ago.

All fail with `Visit function returned an error for Prim` errors

### Apple models
<table>
<tr><th>Model</th><th>Error</th></tr>
<tr><td><a href="https://developer.apple.com/augmented-reality/quick-look/models/vintagerobot2k/robot_walk_idle.usdz"><tt>robot_walk_idle.usdz</tt></a></td><td><tt>Visit function returned an error for Prim /robot_walk_idle/robot_rig/robot_skinned_mesh/robot_mesh_robot_geo/robot_mesh_mesh_export_neck_PLY (id 33)
(file: src/tydra/scene-access.cc, line: 305)
</tt></td></tr>
</table>

### Tinyusdz issue models
<table>
<tr><th>Model</th><th>Error</th></tr>
<tr><td><a href="https://github.com/syoyo/tinyusdz/files/13725770/Furriers_guild_chest_in_Myslenice.zip"><tt>Furriers_guild_chest_in_Myslenice.usdz</tt></a><br><a href="https://github.com/syoyo/tinyusdz/issues/109">(Tinyusdz issue 109)</a></td><td><tt>Visit function returned an error for Prim /scene/Meshes/Sketchfab_model/MRM_AH_252_Skrzynka_cechu_kusnierzy_obj_cleaner_gles/Object_2/Object_3/Object_0 (id 31) 
(file: src/tydra/scene-access.cc, line: 305)
</tt></td></tr>
<tr><td><a href="https://github.com/syoyo/tinyusdz/files/14047718/untitled.usdz.zip"><tt>untitled.usdz</tt></a><br><a href="https://github.com/syoyo/tinyusdz/issues/115">(Tinyusdz issue 115)</a></td><td><tt>Visit function returned an error for Prim /untitled/SkinnedMeshes/blmh/blmh/mh_prim1 (id 14) 
(file: src/tydra/scene-access.cc, line: 305)
</tt></td></tr>
<tr><td><a href="https://github.com/syoyo/tinyusdz/files/13885625/Netsuke_-_Shoki_capturing_an_oni.zip"><tt>Netsuke_-_Shoki_capturing_an_oni.usdz</tt></a><br><a href="https://github.com/syoyo/tinyusdz/issues/116">(Tinyusdz issue 116)</a></td><td><tt>Visit function returned an error for Prim /scene/Meshes/Sketchfab_model/_71218_mia329_030519_501_50Kmesh_OBJ_obj_cleaner_materialmerger_gles/Object_2/Object_0 (id 13) 
(file: src/tydra/scene-access.cc, line: 305)
</tt></td></tr>
</table>

### USD-WG models

<table>
<tr><th>Model</th><th>Error</th></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/full_assets/CarbonFrameBike/CarbonFrameBike.usdz"><tt>CarbonFrameBike.usdz</tt></a></td><td><tt>Visit function returned an error for Prim /CarbonFrameBike/Geom/CarbonFrameBike/Bike_v2/Rahmen/Rahmen_3/Federachse/RadHinten/ZB_HR/HR_Nabe_Tune_Kong_MK_150mm/HR_Nabe_Tune_Kong_MK_150mm_66801/Shape_10361 (id 128)
(file: src/tydra/scene-access.cc, line: 305)
</tt></td></tr><tr><td><a href="https://github.com/usd-wg/assets/blob/main/test_assets/USDZ/CesiumMan/CesiumMan.usdz"><tt>CesiumMan.usdz</tt></a></td><td><tt>Visit function returned an error for Prim /CesiumMan/Geom/Z_UP/Armature/Skeleton_torso_joint_1_3/Cesium_Man_2 (id 8)
(file: src/tydra/scene-access.cc, line: 305)
</tt></td></tr>
<tr><td><a href="https://github.com/usd-wg/assets/blob/main/test_assets/USDZ/DamagedHelmet/DamagedHelmet.usdz"><tt>DamagedHelmet.usdz</tt></a></td><td><tt>Visit function returned an error for Prim /DamagedHelmet/Geom/node_damagedHelmet__6514 (id 12) 
(file: src/tydra/scene-access.cc, line: 305)
</tt></td></tr>
</table>

### Sketchfab models
<table>
<tr><th>Model</th><th>Error</th></tr>
<tr><td><a href="https://sketchfab.com/3d-models/compsognathus-762fd4e099b640aeb6e3341aec042cea"><tt>compsognathus.usdz</tt></a></td><td><tt>Visit function returned an error for Prim /scene/SkinnedMeshes/Sketchfab_model/root/GLTF_SceneRootNode/compsognathus_amature_71/GLTF_created_0/GLTF_created_0_rootJoint/skin0/mesh_0 (id 16) 
(file: src/tydra/scene-access.cc, line: 305)
</tt></td></tr>
</table>

**Comment by syoyo** [comment]
If you find an issue, you should report it with reproducible procedure.

FYI, DamagedHelmet.usdz can now be converted to .obj using `tydra_to_renderscene`.

https://github.com/syoyo/tinyusdz/issues/148#issuecomment-2059826040
