### ISSUE TITLE
Parsing error on a specific file

### ISSUE THREAD

**Issue by MootoolsSoftware** [syoyo/tinyusdz#168]
Branch dev [sync 11/06/2024]

The following USDZ file [https://content.3dmanager.app/permalinks/5001556317-standard.usdz](url) produces the following error when being read using tinyusdz::LoadUSDZFromFile.

The reported error is:

[error].\tinyusdz\src\usdc-reader.cc:ReconstructStage():3438 Failed to reconstruct Stage(Prim hierarchy)
[error].\tinyusdz\src\usdc-reader.cc:ReconstructPrimFromTypeName():1769 Failed to reconstruct Prim Shader elementName: primvar_st0
[error].\tinyusdz\src\prim-reconstruct.cc:ReconstructPrim():4779 Failed to Reconstruct UsdPrimvarReader_float2
[error].\tinyusdz\src\prim-reconstruct.cc:ReconstructShader():4254 Parsing attribute `inputs:fallback` failed. Error: Converting Attribute data failed. Maybe TimeSamples have values with different types?
Failed to load USDC: [5001556317-standard.usdz].

**Comment by syoyo** [comment]
You should provide reproducible procedure.

In the recent `dev` branch,

```
$ tusdcat 5001556317-standard.usdz
$ tydra_to_renderscene 5001556317-standard.usdz
```

works well. Probably the issue has been fixed in this commit: https://github.com/syoyo/tinyusdz/commit/8a5491db31a28b469ec944eba0f157ca62aa0f33

**Comment by MootoolsSoftware** [comment]
I've updated the code and confirm that it is working well know (our code was pulled just before the correction).
