### ISSUE TITLE
No geom returned by tydra::ListPrims

### ISSUE THREAD

**Issue by MootoolsSoftware** [syoyo/tinyusdz#169]
[Crayon.zip](https://github.com/user-attachments/files/15870956/Crayon.zip)

No geom is accessible from the following file using the following code:

```
    std::string warn;
    std::string err;

    tinyusdz::Stage stage;
    tinyusdz::USDZAsset usdz_asset;
    tinyusdz::AssetResolutionResolver arr;
    tinyusdz::LoadUSDFromFile("Crayon.geom.usd", &stage, &warn, &err);

    MeshMap meshmap;
    tinyusdz::tydra::ListPrims(stage, meshmap);
    // Parse all geoms
    for (const auto& item : meshmap) // meshmap is empty
    {
       ...
```

In 3ds max, the import give the following result:
![pencil](https://github.com/syoyo/tinyusdz/assets/15813085/7c263134-9c09-4d4a-bdd1-2d4f2646a303)

**Comment by syoyo** [comment]
Crayon's geom is composed of Variants.

Variant is not well supported in USDC parser and Tydra API at the moment.

FYI,you'll get the following warning in tusdcat
 
```
$ tusdcat Crayon.geom.usd
...
WARN : [warn]/home/syoyo/work/tinyusdz/src/usdc-reader.cc:AddVariantChildrenToPrimNode():383 Multiple Field with VariantSet SpecType detected.
```
