### ISSUE TITLE
Load fails due to Attribute `doubleSided` 

### ISSUE THREAD

**Issue by MootoolsSoftware** [syoyo/tinyusdz#171]
From [https://openusd.org/release/dl_city_set.html](url)

The following file fails. doubleSided attribute make the whole file being not readed.
Could such attribute could be skipped if not recognized, because they are not essential attribute.

* tydra_to_renderscene.exe ".\PointInstancedMedCity\PointInstancedMedCity.usd"

ERR : [error]D:\Manu\Dev_Release\Contrib\tinyusdz\src\usdc-reader.cc:ReconstructStage():3438 Failed to reconstruct Stage(Prim hierarchy)
[error]D:\Manu\Dev_Release\Contrib\tinyusdz\src\usdc-reader.cc:ReconstructPrimFromTypeName():1748 Failed to reconstruct Prim Mesh elementName: mesh_0
[error]D:\Manu\Dev_Release\Contrib\tinyusdz\src\prim-reconstruct.cc:ReconstructGPrimProperties():2750 Parsing attribute `doubleSided` failed. Error: Attribute `doubleSided` must be `uniform` variability.

**Comment by syoyo** [comment]
This is related to https://github.com/syoyo/tinyusdz/issues/135#issuecomment-2041153203

`doubleSided` should be `uniform` attribute according to the schema. https://github.com/PixarAnimationStudios/OpenUSD/blob/2864f3d04f396432f22ec5d6928fc37d34bb4c90/pxr/usd/usdGeom/schema.usda#L623

You can ask around to pxrUSD/OpenUSD community about `varying` attribute(non `uniform`) is allowed where the schema is qualified with `uniform`

**Comment by MootoolsSoftware** [comment]
Yes, looking at the spec, it should be uniform, but nothing prevent it to be a varying attribute. In such case, should the parser fails.

Question to OpenUSD: https://github.com/PixarAnimationStudios/OpenUSD/issues/3127

Answer from AI:
However, while USD itself is quite flexible, and you could technically animate any attribute by using time-sampled data, doing so for attributes like doubleSided is unconventional and might not be supported by all USD-compatible tools and renderers. Animating such attributes would be unusual and could lead to unexpected behavior or performance issues.

**Comment by MootoolsSoftware** [comment]
Here is their answer:
https://github.com/PixarAnimationStudios/OpenUSD/issues/3127#issuecomment-2179502336

**Comment by syoyo** [comment]
As commented here, https://github.com/PixarAnimationStudios/OpenUSD/issues/3127#issuecomment-2181235970

tinyusdz choose to report such inconsistencies as error, until validation framework is ready. You can reopen the issue after USD validation framework is provided.
