### ISSUE TITLE
Confusion about USDLoadOptions

### ISSUE THREAD

**Issue by MootoolsSoftware** [syoyo/tinyusdz#173]
TinyUSD dev branch, updated on June, 17 2024

USDLoadOptions provides different options for handling sublayers, references...

We are working on kitchen set but do not succeed to get access to the geometry.
kitchen set seems to be handled correctly but we probably do not operate in the right way.

![image](https://github.com/syoyo/tinyusdz/assets/15813085/8e78d4eb-db88-4d33-9756-b464e1ed0935)

Here is the shot code we use:
```
tinyusdz::USDLoadOptions usdoptions;
usdoptions.do_composition = true;
usdoptions.load_references = true;
usdoptions.load_payloads = true;
usdoptions.load_sublayers = true;

tinyusdz::Stage stage;
tinyusdz::USDZAsset usdz_asset;
tinyusdz::AssetResolutionResolver arr;

bool ret = tinyusdz::LoadUSDFromFile(filename, &stage, &warn, &err, usdoptions);

MeshMap meshmap;
tinyusdz::tydra::ListPrims(stage, meshmap);

for (const auto& item : meshmap) // <- Mesh map is empty
```

So, how to get access to the kitchen set data?
What is the proper way to achieve this?
Should we use Stage?

Thanks!

**Comment by syoyo** [comment]
Composition is work-in-progress, and at least you should use LoadLayer(construct Layer/PrimSpec).

https://github.com/syoyo/tinyusdz/blob/7f3ae22884cfa8e1834f1750c30c807f0df466c6/examples/tusdcat/main.cc#L120

You can contribute to test with Kitchen set, investigate composition issues, and submit the fix(if the fix needed)

And I'm planning to deprecate composition flags in USDLoadOptions. These are added before implementing `LoadLayer` API.

**Comment by AMZN-Gene** [comment]
Running into the same issue with kitchen_set, and hoping to resolve it. 
Strangely, even directly loading the geom assets (like assets/woodenspoon/woodenspoon.geom.usd) `tydra::ListPrims(stage, meshmap)` is failing to find any tinyusdz::GeomMesh's. 
However, I can clearly see output printing the faces and vertices.
![image](https://github.com/user-attachments/assets/add839fd-edc2-4c81-a8c3-1b8c12e73761)

**Comment by syoyo** [comment]
> Running into the same issue with kitchen_set, and hoping to resolve it.

You can contribute to test with Kitchen set, investigate composition issues, and submit the fix(if the fix needed)

**Comment by AMZN-Gene** [comment]
> > Running into the same issue with kitchen_set, and hoping to resolve it.
> 
> You can contribute to test with Kitchen set, investigate composition issues, and submit the fix(if the fix needed)

Aye. I think I found where in the stage tree the mesh is stored. Might just a matter of updating [TraverseRec ](https://github.com/lighttransport/tinyusdz/blob/a841a471e6951fa60570c47b996562e049678e93/src/tydra/scene-access.cc#L70) to ensure it visits every node properly. Stay tuned...

I wanted to mention even loading woodenspoon.geom.usd _directly_ is failing to load. I believe "composition" doesn't play any part there, since i'm loading the geom file directly. I can turn off subLayers, inherits, variantSets, references, and payloads and _still_ see the mesh data is loaded into memory.  I'm new to USD, so was thinking this might shed light for experienced users to point me in a better direction.

**Comment by syoyo** [comment]
> Might just a matter of updating [TraverseRec ](https://github.com/lighttransport/tinyusdz/blob/a841a471e6951fa60570c47b996562e049678e93/src/tydra/scene-access.cc#L70)to ensure it visits every node properly. Stay tuned...

👍 I think it should visit every GeomMesh Prim in the Stage hierarchy correctly, but may have some issues somewhere.

> I'm new to USD, so was thinking this might shed light for experienced users to point me in a better direction.

You can enable `TINYUSDZ_DEBUG_PRINT` in cmake https://github.com/lighttransport/tinyusdz/blob/a841a471e6951fa60570c47b996562e049678e93/CMakeLists.txt#L171  to print `DCOUT` debug printf macro. It should help a lot!

**Comment by syoyo** [comment]
@AMZN-Gene Running tydra_to_renderscene example is also worth to try:  https://github.com/lighttransport/tinyusdz/tree/dev/examples/tydra_to_renderscene 

https://github.com/lighttransport/tinyusdz/issues/148

It reads USD and convert to OpenGL/Vulkan friendly data structure(e.g. triangulate all meshes), and has a feature to output the result as  .obj and USD(again).  These result can be opened in the Blender 4.1+.

**Comment by syoyo** [comment]
@AMZN-Gene Ah, `assets/woodenspoon/woodenspoon.geom.usd` contains Variants(variantSet), which is not supported in TinyUSDZ Tydra `ListPrims` API  at the moment.

```
    variantSet "modelingVariant" = {
        "WoodenSpoonA" {
            def Xform "Geom"
            {
                def Mesh "WoodenSpoon" (
                    hidden = true
                )
                {
```

https://github.com/lighttransport/tinyusdz/issues/169

You can sponsor TinyUSDZ project to increase the priority of the supporting (nested) Variants https://github.com/lighttransport/tinyusdz/issues/94 , or contribute implementing (nested) Variants in TinyUSDZ.

**Comment by AMZN-Gene** [comment]
Beautiful! Noticing that now too... earlier I thought "composition" wouldn't be required, but indeed, composition feature includes "variants". [tusdcat](https://github.com/syoyo/tinyusdz/blob/7f3ae22884cfa8e1834f1750c30c807f0df466c6/examples/tusdcat/main.cc#L120) includes checking for variants, but ListPrims still doesn't find this: 
```
stage._root_nodes[0]._variantSets["modelingVariant"].second.varientSet.second._primChildren[0]._children[0]._prim_type_name = "Mesh"
```

I'll continue the conversation at #94.
