### ISSUE TITLE
Error Parsing Houdini Solaris Exports

### ISSUE THREAD

**Issue by parsaiej** [syoyo/tinyusdz#183]
Hello, I get the following parse errors when I attempt to load a fully flattened and exported USD stage from Houdini Solaris.

> [error]C:\Development\Vulkan-RayTraced-Indirect\External\tinyusdz\src\usdc-reader.cc:ReconstructStage():3475 Failed to reconstruct Stage(Prim hierarchy)
[error]C:\Development\Vulkan-RayTraced-Indirect\External\tinyusdz\src\usdc-reader.cc[USDC]:ReconstructPrimNode():2387 Failed to parse Prim fields.
[error]C:\Development\Vulkan-RayTraced-Indirect\External\tinyusdz\src\usdc-reader.cc[USDC]:ParsePrimSpec():1953 Failed to validate `apiSchemas`: Invalid or Unsupported API schema: HoudiniViewportGuideAPI

I am wondering if I am perhaps missusing the API (have not done too much more than follow the reference in the README to load my stage). Or this is a broader issue that will require time to fix.

**Comment by syoyo** [comment]
As commented here https://github.com/lighttransport/tinyusdz/issues/170#issuecomment-2174394643

at the moment, unknown apiSchema is reported as an error to avoid potential side-effects.

I may add skipping unknown API when reading in near future.

Also, it is better to support Houdini specific API names to TinyUSDZ. You can list API names used in Houdini, and let us know.

**Comment by syoyo** [comment]
For a while, I made skipping unknown apiSchema by default: https://github.com/lighttransport/tinyusdz/commit/07f05cad0400234497ddd4a5e242c73b8d3e99aa 

This is  TODO: Also, it is better to support Houdini specific API names to TinyUSDZ. You can list API names used in Houdini, and let us know.

Your contribution is much appreciated!
