### ISSUE TITLE
Accessing Reference File Geom

### ISSUE THREAD

**Issue by AMZN-Gene** [syoyo/tinyusdz#186]
Are there any examples for gaining access to referenced file geometry?

**Repro Steps**
1. Update [usdobj-001.usda](https://github.com/lighttransport/tinyusdz/blob/c5443b1c6c1dc5899140f85cf49e9a6f57d39801/models/usdObj-001.usda) to reference [suzanne.usdc](https://github.com/lighttransport/tinyusdz/blob/c5443b1c6c1dc5899140f85cf49e9a6f57d39801/models/suzanne.usdc):
```
def Mesh "suzanne" (
  prepend references = @suzanne.usdc@
)
{
}
```
2. [Load USD as a Layer](https://github.com/lighttransport/tinyusdz/blob/83b4ebc90761e60444e55611238fff6cfb6a62c9/examples/tusdcat/main.cc#L149) `bool ret = tinyusdz::LoadLayerFromFile(filepath, &root_layer, &warn, &err);`
3. [Do compositions (it also returns a layer)](https://github.com/lighttransport/tinyusdz/blob/83b4ebc90761e60444e55611238fff6cfb6a62c9/examples/tusdcat/main.cc#L212) `tinyusdz::CompositeReferences(resolver, src_layer, &composited_layer, &warn, &err)`
4. Then [construct Stage (freezed state) from Layer](https://github.com/lighttransport/tinyusdz/blob/910c5740008377976a559c4ff1680292475abc85/src/composition.hh#L210)
```
bool LayerToStage(const Layer &layer, Stage *stage
```
5. Then call _tinyusdz::tydra::ListPrims_ 
```
std::map<std::string, const tinyusdz::GeomMesh*> meshmap;
tinyusdz::tydra::ListPrims(stage, meshmap);
```

**Expected Results**
meshmap should contain the mesh data for suzanne.usdc

**Actual Result**
I can see the geometry faces and vertices for suzanne are printed, but `GeomMesh* meshmap` is empty

![image](https://github.com/user-attachments/assets/8cd92fbd-718a-40ef-bbfb-b8541902767d)

I'll call, and received back a source layer without any warnings or errors, but unsure how to extract the suzanne geometry.

**Comment by syoyo** [comment]
You cannot reference USD in `def` GeomMesh(or Prim). pxrUSD's usdcat reports error. You should use `subLayers` in Stage metadata.

You can import .obj through`reference` in TinyUSDZ, 

```
tusdcat usdobj-001.usda --flatten
```

but this is tinyusdz's usdObj extension, so the behavior may be different compared to pxrUSD(OpenUSD)'s usdObj.

**Comment by syoyo** [comment]
And as you may see the tusdcat code, if you do the composition, 

- you first need to load USD as a Layer,
- then do compositions(it also produces Layer)
- then construct Stage(freezed state) from Layer https://github.com/lighttransport/tinyusdz/blob/910c5740008377976a559c4ff1680292475abc85/src/composition.hh#L210 
- then call ` tinyusdz::tydra::ListPrims`

**Comment by syoyo** [comment]
> You should use subLayers in Stage metadata.

Ah, I forgot referencing usd through `over` Prim is possible. But its a bit complicated.

https://openusd.org/release/glossary.html#usdglossary-layerstack

**Comment by AMZN-Gene** [comment]
Thank you!

**Comment by AMZN-Gene** [comment]
> And as you may see the tusdcat code, if you do the composition,
> 
> * you first need to load USD as a Layer,
> * then do compositions(it also produces Layer)
> * then construct Stage(freezed state) from Layer https://github.com/lighttransport/tinyusdz/blob/910c5740008377976a559c4ff1680292475abc85/src/composition.hh#L210
> * then call ` tinyusdz::tydra::ListPrims`

I've used the tusdcat with `--flatten --composition=r` and get [src_layer](https://github.com/lighttransport/tinyusdz/blob/83b4ebc90761e60444e55611238fff6cfb6a62c9/examples/tusdcat/main.cc#L197)
I then attempt to get geom, but meshmap is still empty.
```
  tinyusdz::LayerToStage(src_layer, &stage, &warn, &err);
  std::map<std::string, const tinyusdz::GeomMesh*> meshmap;
  tinyusdz::tydra::ListPrims(stage, meshmap);
```

**Comment by syoyo** [comment]
You should not post unreproducible thing. You should post an issue with reproducible procedures and minimal test files/code. And you should first dump  composited Stage(Stage::ExportToString) and confirm it contains GeomMesh

**Comment by AMZN-Gene** [comment]
> You should not post unreproducible thing. You should post an issue with reproducible procedures and minimal test files/code. And you should first dump composited Stage(Stage::ExportToString) and confirm it contains GeomMesh

Repro steps added.
I can see the geometry faces and vertices are printed
![image](https://github.com/user-attachments/assets/8cd92fbd-718a-40ef-bbfb-b8541902767d)

**Comment by syoyo** [comment]
Good. but `Mesh` in `Mesh` in the screenshot is invalid USD.

```
def Mesh "suzanne" (
  prepend references = @suzanne.usdc@
)
{
}
```

TinyUSDZ should report error/warning when referencing `usd` in `def` Prim without prim path, so this should be a tinyusdz's bug. 

And you are better to use subLayers for a while if you want to include USD scene

https://openusd.org/release/glossary.html#usdglossary-sublayers

**Comment by syoyo** [comment]
FYI OpenUSD's `usdcat --flatten` 's result.

```
usdcat --flatten test.usda                                                                
Warning: in _ReportErrors at line 2971 of /home/syoyo/work/USD/pxr/usd/usd/stage.cpp -- In </bora>: Unresolved reference prim path @/home/syoyo/work/tinyusdz/models/suzanne.usdc@<defaultPrim> introduced by @test.usda@</bora> (instantiating stage on stage @test.usda@ <0x56496380db40>) 

#usda 1.0
(
    doc = """Generated from Composed Stage of root layer /home/syoyo/work/tinyusdz/models/test.usda                                   """
)

def Mesh "bora"  {
}
```

**Comment by syoyo** [comment]
Further FYI, specify the prim path(which Prim path is referenced) as shown below should work both for usdcat and tinyusdz

```
def Mesh "suzanne" (
  prepend references = @suzanne.usdc@</Suzanne/Suzanne>
)
{
}
```

Then you'll be able to find GeomMesh in `tydra::ListPrim`

**Comment by AMZN-Gene** [comment]
Ah, that makes sense... I can validate that /Suzanne/Suzanne hierarchy inside of Omniverse USDComposer.
![image](https://github.com/user-attachments/assets/4b34f088-3088-4e39-82e1-4e91661c65cb)

Unfortunately, I'm still getting an empty map when using _@suzanne.usdc@</Suzanne/Suzanne>_ with `tydra::ListPrim` after calling LayerToStage with the composited reference layer.
I'll take your suggestion and check out sub-layers instead.

**Comment by syoyo** [comment]
> I'm still getting an empty map 

Ah, LayerToStage is not yet implemented...

https://github.com/lighttransport/tinyusdz/blob/4e31d4ecf37f64f174a6a39310fbe8d175c1d7be/src/composition.cc#L1330

**Comment by syoyo** [comment]
> Ah, LayerToStage is not yet implemented...

Pushed initial working LayerToStage in this commit: https://github.com/lighttransport/tinyusdz/commit/08dcdc4fe3ac7f70d4e59648521c3fa6c71d1f8c

**Comment by AMZN-Gene** [comment]
I've validated that https://github.com/lighttransport/tinyusdz/commit/08dcdc4fe3ac7f70d4e59648521c3fa6c71d1f8c works! Thank you :D
