### ISSUE TITLE
Too Many Skeletons in Render Scene

### ISSUE THREAD

**Issue by AMZN-Gene** [syoyo/tinyusdz#194]
Toy Drummer Asset contains as many skeletons as meshes (41). There only needs to be one skeleton driving this model.

**Repro Steps**
1. Download Apple's toy drummer idle USD file.
https://developer.apple.com/augmented-reality/quick-look/models/drummertoy/toy_drummer_idle.usdz
[toy_drummer_idle.zip](https://github.com/user-attachments/files/17369921/toy_drummer_idle.zip)
2. Import the asset and create a render scene
```
int main(int argc, char** argv) 
{
    const std::string filePath = "C:/Users/genewalt/Downloads/toy_drummer_idle.usdz";
    tinyusdz::USDLoadOptions options;
    tinyusdz::Stage stage;

    tinyusdz::tydra::RenderScene render_scene;
    tinyusdz::tydra::RenderSceneConverter converter;
    tinyusdz::tydra::RenderSceneConverterEnv env(stage);
    std::string usd_basedir = tinyusdz::io::GetBaseDir(filePath);
    env.set_search_paths({ usd_basedir });
    tinyusdz::USDZAsset usdz_asset;
    std::string warn, err;
    LoadUSDZFromFile(filePath, &stage, &warn, &err, options);
    tinyusdz::ReadUSDZAssetInfoFromFile(filePath, &usdz_asset, &warn, &err);

    tinyusdz::AssetResolutionResolver arr;
    tinyusdz::SetupUSDZAssetResolution(arr, &usdz_asset);
    converter.ConvertToRenderScene(env, &render_scene);
    printf("Skeleton count: %i", render_scene.skeletons.size());
    
    return 0;
}
```
3. Debug render_scene.skeletons or view the print statement
4. Notice there are 41 skeletons which appear to be duplicates. `Skeleton count: 41`

**Expected Results**
There only needs to be one skeleton

**Comment by syoyo** [comment]
You should attach minimal reproducible code + log output

**Comment by AMZN-Gene** [comment]
> You should attach minimal reproducible code + log output

Sorry, I forgot to add the `LoadUSDZFromFile` call. Updated.

**Comment by syoyo** [comment]
Good find! Confirmed the issue also with `tydra_to_renderscene`  example. 

The issue is here:

https://github.com/lighttransport/tinyusdz/blob/aef051388d3a67bf320cf17b7bd51e1018b81534/src/tydra/render-data.cc#L3713

Skeleton path is compared with Mesh Prim path(`abs_path`), so a Skeleton Prim is added(duplicated) for each Mesh accidentally. Fix will be soon.

**Comment by syoyo** [comment]
Found Animation(`SkelAnimation`) is also duplicated.

Output from `tydra_to_renderscene`

```
...
default_root_node 0
// # of Root Nodes : 1
// # of Meshes : 41
// # of Skeletons : 41
// # of Animations : 41
...
````

This will be also fixed.
