### ISSUE TITLE
Failed models from "Kitchen" scene.

### ISSUE THREAD

**Issue by fynv** [syoyo/tinyusdz#24]
[geo.zip](https://github.com/syoyo/tinyusdz/files/9605258/geo.zip)

Uploading 2 of the models tinyusdz currently cannot parse.

Not sure if these are because of compositions. These models are the leaf nodes of reference chains.
Is it because of missing information from the referencing context so we cannot parse them separately?

**Comment by syoyo** [comment]
Therse files contains VariantSelectionMap which is a composition feature and not yet supported in TinyUSDZ.

```
tinyusdz/src/crate-reader.cc:UnpackValueRep():2987 Invalid data type(or maybe not supported in TinyUSDZ yet) for Inlined value: VariantSelectionMap
```

I may try to accept it as a workaround(do parsing, but do nothing and print warnings)

**Comment by fynv** [comment]
Just wondering, for USDC->USDA, is it possible to do without fully loading the stage? 
Could be very helpful to look at the content of a USDC file.

**Comment by syoyo** [comment]
@fynv USDC itself allow delayed load of content. TinyUSDZ currently fully load content in parsing. Delayed loading is related to Compositions so TinyUSDZ may support delayed loading feature once compositions feature has been implemented(not so soon).

**Comment by syoyo** [comment]
Skip parsing composition arcs data in this commit: https://github.com/syoyo/tinyusdz/commit/a91321386f942d6663a7b25bed5d95ea6047c0f5

At least it loads without error. Composition arcs feature(e.g. `over` specifier) are missing in reconstructed Stage data.

**Comment by fynv** [comment]
Yes, I'm able to load the mesh data from "Book" now. 
Thanks! We can close this now, or not, if you prefer to keep tracking.

**Comment by syoyo** [comment]
> I'm able to load the mesh data from "Book" now.

Good!

I'll plan to keep compositions feature here https://github.com/syoyo/tinyusdz/issues/25
