### ISSUE TITLE
EvaluateXformOps: should "suffix" be considered?

### ISSUE THREAD

**Issue by fynv** [syoyo/tinyusdz#27]
Sometimes there is a suffix like ":pivot":
![image](https://user-images.githubusercontent.com/8346412/193207468-bc5edbb5-e9d2-4baf-976f-a47593f1572b.png)

I'm not sure how to perform the transformation in this case. 

EvaluateXformOps currently seems ignoring the suffix. 
Not sure if there should be a fix or not.

**Comment by syoyo** [comment]
You should post `.usda` file, not screenshot.

**Comment by fynv** [comment]
[Ball.udsa.txt](https://github.com/syoyo/tinyusdz/files/9682399/Ball.udsa.txt)

**Comment by syoyo** [comment]
```
uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:translate:pivot", "!invert!xformOp:translate:pivot"]
```

https://github.com/syoyo/tinyusdz/blob/70958f2de9e686bc599a01c7714934f8e07a763b/src/usdGeom.cc#L278

`EvaluateXformOps` should handle `xformOp` attribute with suffixes(i.e, 3 inputs will be passed to `EvaluateXformOps` in the above case), but `!invert!` prefix https://github.com/syoyo/tinyusdz/blob/70958f2de9e686bc599a01c7714934f8e07a763b/src/prim-types.hh#L1647  is not yet considered in `EvaluateXformOps`. Will implement it soon. 

For duplicated output of `xforOp:translate:pivot` and `xformOpOrder` in [Ball.udsa.txt](https://github.com/syoyo/tinyusdz/files/9682399/Ball.udsa.txt), this was another issue of TinyUSDZ. I think recent TinyUSDZ fixed it.

**Comment by syoyo** [comment]
@fynv Not intensively tested yet, but EvaluateXformOps now implements `invert` and RotateABC. Please try recent `dev` branch.

https://github.com/syoyo/tinyusdz/blob/998e317f6aa4e9bd5d945a78660ed30efaa2810c/src/xform.cc#L307

**Comment by fynv** [comment]
Using the new code, "xformOp:translate:pivot" and "!invert!xformOp:translate:pivot" neutralized each other, which seems to be the expected result to me. Closing for now. Thanks!
