### ISSUE TITLE
Prim path questions

### ISSUE THREAD

**Issue by fynv** [syoyo/tinyusdz#32]
1. What's the difference between Prim::path and Prim::elementPath? 
2. Is there a built-in method to get the full-path (absolute path) of a Prim? Seems both  Prim::path and Prim::elementPath return only the name of the node. (Only checked for material nodes).

**Comment by syoyo** [comment]
@fynv Good question!

Coincidently I am working on improving Prim Path thing to support Material binding and Shader graph reconstruction.

1. `Prim::path` could be a  full(?) terminal(leaf) prim path which may contain Property name, Variant name and other infos related to Composition. `Prim::elementPath` only contains leaf name(i.e. the name of the node). pxrUSD uses `element` term as a "terminal"(leaf) name of the prim. https://graphics.pixar.com/usd/dev/api/class_sdf_path.html#a3c38dfddbe1085125aec26c846354bb1 

Having both `path` and `elementPath` may be required to support Composition features. For a while, using `Prim::elementPath` should suffice.

2. There is no built-in method to acquire full and absolute path of a Prim(e.g. `/look0/material/tex0`). You'll need to traverse Prim tree and concatenate elementPath name to get a full and absolute path of a Prim.

I'm starting to write such a method here(not working yet. more to say, found `Stage::GetPrimAtPath` is broken 😩)

https://github.com/syoyo/tinyusdz/blob/dev/examples/tydra_convert/tydra-convert-main.cc

Acquiring full absolute path of a Prim from a Stage will be implemented as a Tydra API soon.

**Comment by fynv** [comment]
Understood. Closing.

**Comment by syoyo** [comment]
Fixed GetPrimAtPath and add some cleanup for Path and Prim class in recent `dev` branch

You can now query a Prim from Stage with abs path. Example is here: https://github.com/syoyo/tinyusdz/blob/f7df4ee90fb1ce4f466ac7cd1ce6ef2f2a66b324/examples/tydra_convert/tydra-convert-main.cc#L212
