### ISSUE TITLE
skeleton.joints.size() == 0

### ISSUE THREAD

**Issue by fynv** [syoyo/tinyusdz#35]
I encountered a strange issue that a tinyusdz::Skeleton from a loaded stage, has a .joints property of length 0.

The stage can be successfully dumped with tinyusdz::usda::SaveAsUSDA(). The "joints" array in the dumped .usda file is not empty.

Related code looks like:

```c++
...
else if (prim.prim->data().type_id() == tinyusdz::value::TYPE_ID_SKELETON)
{
	auto* skel_in = prim.prim->data().as<tinyusdz::Skeleton>();			
	auto& joints = skel_in->joints.GetValue().value();
	printf("%d\n", joints.size()); // prints  0 here
}
```

**Comment by fynv** [comment]
Seems my mistake in using rvalue reference.

"auto& joints =  -> auto joints =" fixes it.

Closing.

**Comment by syoyo** [comment]
It'd be better to avoid using  `nonst::optional` return type for public API. Will consider to provide accessor method for Attribute like this:

`bool Get(T *val)`  

(Similar to pxrUSD)

**Comment by syoyo** [comment]
@fynv Added compiler-friendly and less-confusing `get` method for TypedAttribute: https://github.com/syoyo/tinyusdz/blob/dev/src/prim-types.hh#L949

Also added handy `get` API for builtin attributes in SkelAnimation https://github.com/syoyo/tinyusdz/blob/b1f1bd6c26b2b5c84d48a61e1c4138d94806b3f7/src/usdSkel.hh#L122
(Adding such  `get` methods to other Prims will be soon)
 
Please not that API naming rule is now changed to use Snake case: https://github.com/syoyo/tinyusdz/issues/28
