### ISSUE TITLE
Inconsistency of "material:binding"

### ISSUE THREAD

**Issue by fynv** [syoyo/tinyusdz#39]
* In struct GeomMesh, it is stored in .materialBinding;
* In struct Xform, it is stored as  .props["material:binding"] as a "relationship" value.

**Comment by syoyo** [comment]
You should attach reproducible USD file. Is there a USD which uses `material:binding` in Xform Prim?

`material:binding` is nearly builtin property of GeomMesh(and GeomSubset), so I am defining it as a class variable.
It may be uncommon other Prim class have materialBinding API so you need to access it as a generic(custom) property through `.props`.

It may be worth to have unified way to retrieve MaterialBinding info from a Prim something like `tydra::GetMaterialBindingRelationship(prim)` (also checks if Prim activates `materialBindingAPI`) https://github.com/PixarAnimationStudios/USD/blob/0c7b9a95f155c221ff7df9270a39a52e3b23af8b/pxr/usdImaging/bin/testusdview/testenv/testUsdviewOIT/test.usda#L32 

You can contribute!

**Comment by fynv** [comment]
Pixar HumanFemale is actually a case using `material:binding` in Xform.

The point seems to be letting multiple child Meshes inherit the material:

![image](https://user-images.githubusercontent.com/8346412/200271397-a9acd0ca-26f4-480e-b5ef-a53a68f77614.png)

**Comment by syoyo** [comment]
You should not attach HumanFemale USD. It will violate EULA https://graphics.pixar.com/usd/release/dl_usdskel_examples.html

**Comment by fynv** [comment]
Ok.. removed. It's the flattened data.

**Comment by syoyo** [comment]
:pray: Derivative work(flattened data) is also would not be allowed.

Anyway, its interesting having MaterialBindingAPI in  Xform(its valid though if Prim activates `materialBindingAPI`).
As I described, please use `material:binding` in `.props` for Prim other than GeomMesh and GeomSubset for a while.

**Comment by fynv** [comment]
Ok, closing. Thanks!

**Comment by syoyo** [comment]
@fynv FYI You can check activated `apiSchemas` of each Prim through `PrimMeta::apiSchema` https://github.com/syoyo/tinyusdz/blob/8525a6dd32f1fca3e41503c94eaa1a1cc22e1e0d/src/prim-types.hh#L636
