### ISSUE TITLE
jeaiii_to_text.h

### ISSUE THREAD

**Issue by jeaiii** [syoyo/tinyusdz#45]
Fixed an bug in jeaiii_to_text.h that is in this repo. Please update before enabling.

**Comment by syoyo** [comment]
@jeaiii Thanks for the info! Will update jeaiii soon! BTW I have modified jeaiii to compile on C++14(convert hex-float literal to ordinary floating point constants). Do you accept PR of such modification?

**Comment by jeaiii** [comment]
PRs are welcome, I may go ahead and change it to something like `(u64(1) << 48) / u64(1e6) + 1`

**Comment by syoyo** [comment]
@jeaiii Understand! Will include some tests when submitting PR

**Comment by syoyo** [comment]
PR submitted https://github.com/jeaiii/itoa/pull/13 and merged into jeaiii `main`, and use recent `main` version of jeaiii in TinyUSDZ. So closing the issue.
