### ISSUE TITLE
How to get xform's transform matrix?

### ISSUE THREAD

**Issue by xahon** [syoyo/tinyusdz#48]
I don't know how to access `matrix4d xformOp:transform` in `def Xform "<NAME>"`

**Comment by syoyo** [comment]
You need to traverse Prim tree,  or Get a corresponding Prim(Xform) using https://github.com/syoyo/tinyusdz/blob/127fd2219712c53067acdd9cc480f5f454ca5ced/src/stage.hh#L90

Then cast it to Xform and iterate xformOp to find xformOp: https://github.com/fynv/usd2glb/blob/82980630b10a45ca993859982845b8d0f26c8c0f/main.cpp#L476
