### ISSUE TITLE
How to access material:binding relation from GeomSubset object?

### ISSUE THREAD

**Issue by xahon** [syoyo/tinyusdz#50]
I didn't find an API to get material binding relation like from `GeomMesh` object with `materialBinding` field

**Comment by syoyo** [comment]
https://github.com/syoyo/tinyusdz/blob/41970d1aa8dd94e754c95e78ac159afe93c74337/examples/tydra_api/tydra-api-main.cc#L361

**Comment by syoyo** [comment]
If you are looking for materialBind info from GeomSubset, not GeomMesh, currently handy API is not provided. You may find it through generic Property field `GeomSubset::props` https://github.com/syoyo/tinyusdz/blob/41970d1aa8dd94e754c95e78ac159afe93c74337/src/usdGeom.hh#L388

**Comment by xahon** [comment]
@syoyo `props` field is empty in my case. Looks like a bug then

**Comment by syoyo** [comment]
You can contribute implementing similar API as done in GeomMesh to GeomSubset!

FYI, there are two places you need to look

- USDA: https://github.com/syoyo/tinyusdz/blob/41970d1aa8dd94e754c95e78ac159afe93c74337/src/usda-reader.cc#L1454
- USDC:  Oh I didn't implemented GeomSubset in USDC reader... https://github.com/syoyo/tinyusdz/blob/41970d1aa8dd94e754c95e78ac159afe93c74337/src/usdc-reader.cc#L1498 https://github.com/syoyo/tinyusdz/blob/41970d1aa8dd94e754c95e78ac159afe93c74337/src/usdc-reader.cc#L357

**Comment by xahon** [comment]
I'd like to contribute but I still can't understand how `GeomSubset` was intended to work. Pixar's API reference for that type is kind of vague and I found no clear description of `Mesh` and `GeomSubset`.  I have an ascii model definition with that structure:
```
-  type Mesh
   points, normals, indices
   -  type GeomSubset
      indices
   -  type GeomSubset
      indices
```
And some indices from both `GeomSubset`s are out of bounds if they are used as indices in `Mesh`'s points array. I think `GeomSubset` is for defining a submesh but then why `Mesh` contains indices at all.

**Comment by syoyo** [comment]
> I'd like to contribute

👍

> I still can't understand how GeomSubset was intended to work

Yeah! Even me :-)

It'd be first look at this:

https://github.com/PixarAnimationStudios/USD/issues/542
https://github.com/PixarAnimationStudios/USD/tree/release/pxr/usdImaging/usdImagingGL/testenv/testUsdImagingGLGeomSubsets

In basic GeomSuset configuration, `GeomSubset::indices` are indices of face id in its parent's `GeomMesh::faceVertexIndices`, not array index of `GeomMesh::points`, since GeomSubset is usually  for representing per-face materials of GeomMesh.

**Comment by xahon** [comment]
I found out that `indices` in `GeomSubset` are not indices at all. It's a face offset in main `Mesh` indices array. I mean that if you have (Pseudo USD)
```
Mesh:
    faceVertexCounts = [4, 4, 4, 4]
    faceVertexIndices = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
   
    GeomSubset:
        indices = [3]
```
Then you want to access indices at `faceVertexIndices[sum(faceVertexCounts[0], faceVertexCounts[3])]` with subarray length of `faceVertexCounts[3]`

In other words to access `N`th `GeomSubset`'s face you want to calculate:
```
size_t offset = 0;
for (size_t i = 0; i < N; i++) offset += faceVertexIndices[i];
uint32_t *faceIndices = faceVertexIndices[offset];
size_t faceIndicesCount = faceVertexCounts[N];
```

I made a helper structure that firstly builds an array of polygon data in O(N) in my user code, then I can easily triangulate them into my custom mesh format

If you first build a faces array then `GeomSubset` indices will be indices into that array

**Comment by syoyo** [comment]
MaterialBinding API is finally supported in `dev` branch.

You can look into https://github.com/syoyo/tinyusdz/blob/dev/src/tydra/render-data.cc for how to use it.
It also contains how to process indices in GeomSubset(e.g. rebuild indices in GeomSubset in trinangulation)
