### ISSUE TITLE
Can this library triangulate all meshes and its subsets?

### ISSUE THREAD

**Issue by xahon** [syoyo/tinyusdz#51]
I have a model with `faceVertexCounts` == 4. In order to use it in my program I need to triangularize whole model, i.e. make each polygon from 3 vertices. Seems like Pixar's library has something like that (https://graphics.pixar.com/usd/dev/api/class_hd_mesh_util.html) but judging from the signature it's unable to triangularize `Mesh` with respect to its `GeomSubset`s

**Comment by syoyo** [comment]
There is a mesh triangulation code https://github.com/syoyo/tinyusdz/blob/57547ec9a12fdbff0cdb02df014abbce08cdca19/src/tydra/render-data.cc#L156

But no support for primvars yet. Not sure GeomSubset's indices is affected by triangulation. You can contribute extending Triangulator considering primvars and GeomSubset indices(if triangulation is really needed to be considered)

**Comment by syoyo** [comment]
Tydra API now supports triangulation of meshes including predefined primvars and subset indices.

See this code.

https://github.com/syoyo/tinyusdz/blob/dev/src/tydra/render-data.cc
