### ISSUE TITLE
Doesn't load models from pixar samples and stocks

### ISSUE THREAD

**Issue by xahon** [syoyo/tinyusdz#62]
I've tried to load models from pixar [HumanFemale](https://graphics.pixar.com/usd/release/dl_usdskel_examples.html) and the reader can't parse it (Blender does)  
```
import: Couldn't load USD. Failed to parse USDA
[error]/home/dev/tinyusdz/src/usda-reader.cc:Read():1676 Parse failed:Near line 13, col 27: Failed to parse `def` block.

Near line 13, col 27: [error]/home/dev/tinyusdz/src/ascii-parser.cc:ParsePrimMetas():2952 Failed to parse Meta value.

Near line 13, col 27: Failed to parse Prim meta value.

Near line 13, col 27: [error]/home/dev/tinyusdz/src/ascii-parser.cc:ParseMetaValue():2360 String literal expected for `variantSets`.

Near line 13, col 27: [error]/home/dev/tinyusdz/src/ascii-parser.cc:ReadStringLiteral():1080 String or Token literal expected but it does not start with " or '
```

I also have problems with loading a random model from stocks, for example [this rock model](https://www.cgtrader.com/items/898927/download-page)  
```
import: Couldn't load USD. [error]/home/dev/tinyusdz/src/usdc-reader.cc[USDC]:ParsePrimSpec():1610 Invalid token for `kind` Prim metadata: `Material`
[error]/home/dev/tinyusdz/src/usdc-reader.cc[USDC]:ReconstructPrimNode():1997 Failed to parse Prim fields.
[error]/home/dev/tinyusdz/src/usdc-reader.cc:ReconstructStage():2412 Failed to reconstruct Stage(Prim hierarchy)
```

**Comment by syoyo** [comment]
Compoisition feature is work-in-progress, so you need first flatten USD model using `usdcat --flatten` for HumanFemale model.

> I also have problems with loading a random model from stocks, 

you should attach minimal & reproducible model, or URLs with publicly accessible models

**Comment by xahon** [comment]
@syoyo yes, i've attached the link to the rock model. It's under a license and I don't risk to share it as a file publicly

**Comment by syoyo** [comment]
FYI TinyUSDZ now can parse HumanFemale usda in recent `dev` branch. But parsing only. No actual composition feature and easy access to variantSet are implemented yet.
