### ISSUE TITLE
Can't load usdz model's material

### ISSUE THREAD

**Issue by AndiosDev2013** [syoyo/tinyusdz#82]
hi @syoyo , I am trying to show the USDZ file using tinyUSDZ library in android device, it is loading vertices and texture coordinates successfully, but can't load materials, can you let me know what's the problem. I attached USDZ file
![image](https://github.com/syoyo/tinyusdz/assets/4025118/65a27085-1555-4403-bb0a-dddedb022568)
Please check files:
https://drive.google.com/drive/folders/18F4Nqv1iWPsuCGPmT6zz_9VnWUTtAQDe?usp=sharing

**Comment by syoyo** [comment]
Material/Shader support in Tydra(convert USD Stage to renderable scene data structure https://github.com/syoyo/tinyusdz/tree/dev/src/tydra , especially `ConvertToRenderScene`  )  is work-in-progress.

https://github.com/syoyo/tinyusdz/blob/8b248ad91e355f7161975c986911576fba16e32e/src/tydra/render-data.cc#L1688

For a while, You need to manually traverse Material/Shader Prim tree and write your own logic.

https://github.com/syoyo/tinyusdz/blob/dev/examples/tydra_api/tydra-api-main.cc

You can also contribute implementing missing features to `ConvertToRenderScene`
