### ISSUE TITLE
Is the C api still supported?

### ISSUE THREAD

**Issue by ThomasConrad** [syoyo/tinyusdz#99]
I saw that the last change to the c api was 6 months ago. I am interested in starting a project that uses rust bindings to the c api. Is it fully supported still and can use compositing and the other features which will come out in the future, or should I instead create my own C wrapper for the library?

**Comment by syoyo** [comment]
C API is still work in progress and has lower priority at the moment. I may resume C API at some point but no ETA.

Your C API contribution is much appreciated!
